// Stamp the build: content-hash version, service-worker precache list, engine manifest.
// Run after any change:  node tools/stamp.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const walk = (dir) => readdirSync(join(ROOT, dir)).flatMap((f) => {
  const p = join(dir, f);
  return statSync(join(ROOT, p)).isDirectory() ? walk(p) : [p];
});

const shell = [
  'index.html',
  'manifest.webmanifest',
  ...walk('src').filter((f) => /\.(js|css)$/.test(f)),
  ...walk('assets/fonts').filter((f) => f.endsWith('.woff2')),
  'assets/icons/icon.svg', 'assets/icons/apple-touch-icon.png', 'assets/icons/icon-192.png', 'assets/icons/icon-512.png', 'assets/icons/maskable-512.png',
].sort();

const engine = [
  'engine/tesseract/tesseract.min.js',
  'engine/tesseract/worker.min.js',
  'engine/tesseract/tesseract-core-simd-lstm.wasm.js',
  'engine/tesseract/tesseract-core-lstm.wasm.js',
  'engine/lang/eng.traineddata.gz',
];

const hash = createHash('sha256');
for (const f of [...shell.filter((f) => f !== 'src/engine-manifest.js'), ...engine]) {
  hash.update(f);
  hash.update(readFileSync(join(ROOT, f)));
}
const version = hash.digest('hex').slice(0, 10);

const files = engine.map((p) => ({ path: p, size: statSync(join(ROOT, p)).size }));
writeFileSync(join(ROOT, 'src/engine-manifest.js'),
  `// Generated by tools/stamp.mjs. Do not edit.\nexport const BUILD = '${version}';\nexport const ENGINE = ${JSON.stringify({ files }, null, 2)};\n`);

let sw = readFileSync(join(ROOT, 'sw.js'), 'utf8');
sw = sw.replace(/const VERSION = '[^']*';/, `const VERSION = '${version}';`);
sw = sw.replace(/const SHELL = \[[\s\S]*?\];/, `const SHELL = ${JSON.stringify(['./', ...shell], null, 2)};`);
writeFileSync(join(ROOT, 'sw.js'), sw);

const total = files.reduce((s, f) => s + f.size, 0);
console.log(`build ${version}: ${shell.length} shell files, engine ${(total / 1048576).toFixed(1)} MB`);
